-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.
create database OficinaMecanicaSomativa;
use OficinaMecanicaSomativa;

CREATE TABLE CLIENTE (
CLI_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL PRIMARY KEY,
CLI_NOME VARCHAR(60) NOT NULL,
CLI_CELULAR VARCHAR(14) NOT NULL,
CLI_CPF VARCHAR(14) NOT NULL,
CLI_CEP VARCHAR(9) NOT NULL,
CLI_DATANASC DATE NOT NULL
);

CREATE TABLE VEICULO (
VEI_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL PRIMARY KEY,
VEI_MODELO VARCHAR(60) NOT NULL,
VEI_MARCA VARCHAR(60) NOT NULL,
VEI_PLACA VARCHAR(60) NOT NULL,
VEI_COR VARCHAR(60) NOT NULL,
CLI_ID INT NOT NULL,
FOREIGN KEY(CLI_ID) REFERENCES CLIENTE(CLI_ID)
);

CREATE TABLE MECANICO (
MEC_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL PRIMARY KEY,
MEC_NOME VARCHAR(60) NOT NULL,
MEC_CPF VARCHAR(14) NOT NULL,
MEC_CELULAR VARCHAR(14) NOT NULL,
MEC_CEP VARCHAR(9) NOT NULL,
MEC_DATANASC DATE NOT NULL
);

CREATE TABLE PECAS (
PE_NOME VARCHAR(60) NOT NULL,
PE_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL PRIMARY KEY,
PE_ESTADO VARCHAR(60) NOT NULL,
PE_DESCRICAO VARCHAR(255) NOT NULL,
PE_VEICULOSCOMPATIVEL VARCHAR(255) NOT NULL,
PE_QTDE INT NOT NULL,
PE_VALOR DECIMAL(6,2) NOT NULL
);


CREATE TABLE SERVICO (
SE_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL PRIMARY KEY,
SE_NOME VARCHAR(60) NOT NULL,
SE_DETALHES VARCHAR(255) NOT NULL,
SE_DATA_INICIO DATE NOT NULL,
SE_DATA_FIM DATE NOT NULL,
SE_STATUS ENUM("ATIVO","FINALIZADO","AGUARDANDO") NOT NULL,
SE_VALOR DECIMAL(6,2) NOT NULL,
PE_ID INT,
VEI_ID INT NOT NULL,
MEC_ID INT NOT NULL,
FOREIGN KEY(VEI_ID) REFERENCES VEICULO (VEI_ID),
FOREIGN KEY(MEC_ID) REFERENCES MECANICO (MEC_ID),
FOREIGN KEY(PE_ID) REFERENCES PECAS (PE_ID)
);





